version: "3.8"

services:

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crypto
      - MONGO_INITDB_ROOT_PASSWORD=Cr7ptopa55

  importer:
    image: importer
    build: ./importer
    restart: always
    depends_on:
      - mongodb
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017

  analyzer:
    image: analyzer
    build: ./analyzer
    restart: always
    depends_on:
      - mongodb
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017
      
  web:
    image: web
    build: ./web
    restart: always
    volumes:
      - ./web/app:/app
    ports:
      - 8000:80
    depends_on: 
      - mongodb
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017
    command:
      - "/start-reload.sh"