version: "3.8"

services:

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./../mongodb/data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crypto
      - MONGO_INITDB_ROOT_PASSWORD=Cr7ptopa55

  importer:
    image: costigator/importer:latest
    restart: always
    depends_on:
      - mongodb
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017

  analyzer:
    image: costigator/analyzer:latest
    restart: always
    depends_on:
      - mongodb
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017
      - ANALYZER_RUN_EVERY_MIN=5

  web:
    image: costigator/web:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 80:80
    environment: 
      - DB_URI=mongodb://crypto:Cr7ptopa55@mongodb:27017
