# general
DB_URI: mongodb://crypto:Cr7ptopa55@localhost:27017
BINANCE_API_URL: https://api.binance.com/api/v1

# stream
STREAM_EXCHANGE_URL: binance.com
STREAM_UPDATE_INTERVAL_S: 5
STREAM_RELOAD_SYMBOLS_EVERY_M: 15

# history
HISTORY_START_DATE: "2021-01-01 00:00:00"
HISTORY_RUN_EVERY_MIN: 60
HISTORY_CHANNELS: kline_1m, kline_5m, kline_15m, kline_1h, kline_4h, kline_1d

# symbols
SYMBOLS_IMPORT_EVERY_M: 5
SYMBOLS_FILTER: USDT
SYMBOLS_COINGEKO_PAGES: 10