name: Docker Images Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'current-version.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build and push images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current version
      id: vars
      run: echo ::set-output name=version::$(cat current-version.txt)
    - name: Save current version in a variable
      env:
        CURRENT_VERSION: ${{ steps.vars.outputs.version }}
    - name: Login to Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build importer Docker image
      run: |
        docker build ./importer -t costigator/importer:latest
        docker build ./importer -t costigator/importer:$CURRENT_VERSION
        docker build ./web -t costigator/web:latest
        docker build ./web -t costigator/web:$CURRENT_VERSION
    - name: Push images to Docker
      run: |
        docker push costigator/importer:latest
        docker push costigator/importer:$CURRENT_VERSION
        docker push costigator/web:latest
        docker push costigator/web:$CURRENT_VERSION
        
