name: Docker Images Deployment

# Run this action only when a new tag is created
on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
 
      # - name: Login to Docker
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # - name: Build importer Docker image
      #   run: |
      #     docker build ./importer -t costigator/importer:latest
      #     docker build ./importer -t costigator/importer:1.0.0
      #     docker build ./web -t costigator/web:latest
      #     docker build ./web -t costigator/web:1.0.0
      # - name: Push images to Docker
      #   run: |
      #     docker push costigator/importer:latest
      #     docker push costigator/importer:1.0.0
      #     docker push costigator/web:latest
      #     docker push costigator/web:1.0.0
        
